#! /bin/bash
clear
export NEWT_COLORS='
root=white,black
window=white,black
textbox=white,black
title=white,black
listbox=white,black
sellistbox=black,yellow
actsellistbox=black,yellow
border=black,blue
actbutton=black,green
button=white,black'

title=" piCorderOs "
verInfo="022322.1129"

#[EN/US]
txtHelloWorld=" Hello World: "
txtexit="Exit "
txtabout="About "
txtContinueYN="Continue "

#[Vulcan]
#txtHelloWorld="Tonk'peh panu  "
#txtexit="Ruken "
#txtabout="Pa' nash "

#[Names]
txtMenu01="install TR-108"
txtMenu02="install TR-109"



function myTestFun {
  
if (whiptail --fb --title "$title" --yesno "$txtContinueYN." 20 60); then
  result="User selected Yes, exit status was $?."
else
  result="User selected No, exit status was $?."
fi

}

aboutConfig=" This tool aims to easly initial configuration piCorderOs. ver#: $verInfo "                         

while [ 1 ]
do

CHOICE=$(
whiptail --fb --nocancel --title "$title" --menu "" 20 60 5 \
	"1)" "$txtMenu01"   \
	"2)" "$txtMenu02"  \
	"3)" "$txtabout " \
	"0)" "$txtexit "  3>&2 2>&1 1>&3	
)

result=$(whoami)
case $CHOICE in
	"1)")   
  myTestFun
	;;
	"2)")   
		result="User $result: PG.2 "
	;;
	"3)")   
		result="User $result: $aboutConfig "
        ;;
	"0)") exit
        ;;
esac
whiptail --fb --msgbox "$result" 20 60
done
exit
